substitutions:
  # Params with default values
  _PROJECT_NAME: backend
  _PROJECT_REGION: europe-west1
  _MEMORY: 1Gi
  _COCURRENCY: "40"
  _TIMEOUT: "30"
  _CONTAINER_REGION: eu.gcr.io

steps:
  # Build Container image
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "${_CONTAINER_REGION}/$PROJECT_ID/${_PROJECT_NAME}:$PROJECT_ID-${SHORT_SHA}"
      - "."

  # Push Container image to Container Repo
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_CONTAINER_REGION}/$PROJECT_ID/${_PROJECT_NAME}:$PROJECT_ID-${SHORT_SHA}"

    # Tag Container image with Project Id
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "container"
      - "images"
      - "add-tag"
      - "${_CONTAINER_REGION}/$PROJECT_ID/${_PROJECT_NAME}:$PROJECT_ID-${SHORT_SHA}"
      - "${_CONTAINER_REGION}/$PROJECT_ID/${_PROJECT_NAME}:$PROJECT_ID-latest"

    # Deploy Container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "deploy"
      - "${_PROJECT_NAME}"
      - "--image"
      - "${_CONTAINER_REGION}/$PROJECT_ID/${_PROJECT_NAME}:$PROJECT_ID-${SHORT_SHA}"
      - "--region"
      - "${_PROJECT_REGION}"
      - "--memory"
      - "${_MEMORY}"
      - "--concurrency"
      - "${_COCURRENCY}"
      - "--timeout"
      - "${_TIMEOUT}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--project"
      - "$PROJECT_ID"
      - "--async"
timeout: 1200s # extend timeout for build to 20 minutes
options:
  logging: CLOUD_LOGGING_ONLY
